version: '3.7'

networks:
  backend_network:

services:

  backend:
    container_name: hospote-api-v1
    restart: on-failure
    build: .
    env_file: .env
    command: uwsgi --socket=:8002 --module=project.wsgi:application --py-autoreload=1
    volumes:
      - .:/app
      - ./static:/app/static
    networks:
      - backend_network

  nginx:
    image: nginx:1.15.0
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
    networks:
      - backend_network
    ports:
      - '8000:80'

