# Generated by Django 3.2 on 2021-12-10 11:53

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('unify', 'unify'), ('standalone', 'standalone')], max_length=50, unique=True)),
                ('host', models.CharField(max_length=150, unique=True)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Controller',
                'verbose_name_plural': 'Controllers',
            },
        ),
        migrations.CreateModel(
            name='PonemusCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.controller')),
            ],
            options={
                'verbose_name': 'Ponemus Customer',
                'verbose_name_plural': 'Ponemus Customers',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('site_name', models.CharField(max_length=200, unique=True)),
                ('site_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('default_group_id', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('container_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, samples=None)),
                ('background_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, samples=None)),
                ('controller', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to='main.controller')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ponemuscustomer')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='CustomerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
                ('user_group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('device', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.site')),
            ],
            options={
                'verbose_name': 'Customer Site',
                'verbose_name_plural': 'Customer Sites',
            },
        ),
    ]
