# Generated by Django 3.2 on 2021-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
